\documentclass[xcolor=dvipsnames,compress,subsection=false]{beamer}
% xcolor=svgnames % even more colors

\usepackage[orientation=landscape,size=custom,width=18,height=10,scale=0.45]{beamerposter} %für breite screens
% \usepackage[orientation=landscape,size=custom,width=16,height=9,scale=0.45,debug]{beamerposter} %für 16:9 ratio

\mode<presentation>{

 \usetheme{Warsaw}
% \usetheme{Frankfurt}
}
% \usecolortheme{lily}
\usecolortheme{beaver}

\input{tex-stuff/preamble_new}


\pdfinfo
{
  /Title       (AniMove 2017: www.animove.org)
  /Creator     (K. Safi)
  /Author      (K. Safi)
}



% inhalt
\title[AniMove 2017]{\textcolor{gray}{September 2017} \\Movement data introduction}
\subtitle{Introduction into movement data collection}
\author[www.animove.org]{www.animove.org}
\institute[AniMove]{MPI for Ornithology}
\date{2017}

%hover command for overlays
\newcommand<>{\hover}[1]{\uncover#2{%
  \begin{tikzpicture}[remember picture,overlay]%
    \draw[fill,opacity=0.4] (current page.south west) rectangle (current page.north east);
    \node at (current page.center) {#1};
  \end{tikzpicture}}
}
% end




\begin{document}
<<setup, include=FALSE>>=
require(knitr)
opts_chunk$set(fig.path='figure/beamer-',fig.align='center',fig.show='hold',size='footnotesize')
@
\tikzstyle{every picture}+=[remember picture]


{\setbeamercolor{background canvas}{bg=black}
\begin{frame}[plain]
 \definecolor{african_dawn}{RGB}{174,162,118}
    \begin{center}
    \leftskip-3em
    \vskip-2em
  \begin{overpic}
    [width=1.15\textwidth,clip=true,trim=0 0 0 00]{graphics/BG_neutral.png}
% 		\put(5,55){\Huge{\textcolor{black}{\textbf{Coffee Break}}}}
% 		\put(5,45){\huge{\textcolor{blue}{\textbf{afterwards: introduction to an R editor}}}}
		\end{overpic}
    \end{center}

\end{frame}
}


\begin{frame}
 
\thispagestyle{empty}

    \vspace{5em}
    \begin{tabular*}{\paperwidth}[b]{p{34em}rr}
         \vskip-2em
          \leftskip-2.88em     \includegraphics[height=.7cm]{graphics/logo/unilogo.jpg} \hspace{0.2cm} \includegraphics[height=.7cm]{graphics/logo/dlr.jpg} \hspace{0.2cm} \includegraphics[height=.7cm]{graphics/logo/mpi_logo2.jpg} \hspace{0.2cm} \includegraphics[height=.7cm]{graphics/logo/enb} \hspace{0.2cm} \includegraphics[height=.7cm]{graphics/logo/Smithsonian_large.jpg} \hspace{0.2cm} \includegraphics[height=.7cm]{graphics/logo/ZSL_black.jpg} \hspace{0.2cm} \includegraphics[height=.7cm,clip=true,trim=0 0 0 0]{graphics/logo/gce.jpg}&  &           
    \end{tabular*}

          \leftskip-12.5em%
          \vskip-.3em
          \includegraphics[width=1.38\textwidth,clip=true,trim=0 150 0 0]{graphics/gradient_giraffe_RS}
    
%Bereich unter dem Bild:
            \leftskip-6.5em%
            \vskip1.5em%
%                	\hspace{0.5cm}
             \begin{tabular*}{\paperwidth}[b]{p{18em}p{20em}} 
%Titel der Präsentation:
		  &  \\
% 		  & \\
                 &  \parbox{25em}{\begin{large}\inserttitle\end{large}}\\%
                  \\
% 		  &  \\
% % 		  & & \\
               	\hspace{1.5cm}
		 \textcolor[rgb]{0,0,0}{  \parbox[t]{20.5em}{\tiny \insertauthor\ $\vert$  \insertinstitute}}%
%Untertitel der Präsentation:
               &  {\parbox{25em}{\insertsubtitle}}\\%
             \end{tabular*}
  \vfill
\end{frame}

%%%%%%%%%%%%%%%% begin slides here %%%%%%%%%%%%%%%%

\begin{frame}[fragile]{Data types}
Two fundamental types of movement data
  \begin{itemize}
  \item{Lagragian methods}
  \begin{itemize}
  \item[-]{Radio tracking}
  \item[-]{Satellite tracking}
  \item[-]{GPS}
  \item[-]{Geo-locators}
  \end{itemize}
  \vspace{3mm}
  \item{Eulerian methods}
  \begin{itemize}
  \item[-]{Camera traps}
  \item[-]{Rings and bands}
  \item[-]{RFID tags}
  \item[-]{Microphon arrays}
  \end{itemize}
\end{itemize}
\end{frame}


\begin{frame}{Data structures: Eulerian}
\begin{columns}
\column{0.5\textwidth}
Eulerian methods are posing great challenges. Most methods and analysis assume unbiased sampling (more to follow). Eulerian methods are violating the unbiased sampling assumption in the spatial domain. However, the data they provide allow often in specific systems quite a reliable reconstruction of paths. Especially in movements along grids (fish in rivers).\\
Nicolas Perony has a nice example: 10.1371/journal.pcbi.1002786
  \column{0.45\textwidth}
  \begin{figure}
  \centering
\includegraphics[width=1\textwidth]{graphics/perceptual_landscape_thumb_600x600.png}
    \end{figure}
    \end{columns}
\end{frame}

%\begin{frame}{Data structures: Eulerian data}
%\includemovie{\textwidth}{0.5\textwidth}{Boris+Bikes+redux-HD.mp4}
%\end{frame}

\begin{frame}{Data structures: Lagragian}
Movement is defined as a sequence of locations in time. Usually we think of and work with movement data where the position of an animal is collected through a device attached to the animal that allows in principle knowing where the animal is at any time: Lagragian data. The different methods differ mainly in their precision. The error in location estimation needs to be accounted for and we have to be aware of it, when we analyse data.

\end{frame}
\begin{frame}{Data structures: Lagragian}
\vspace{-0.5mm}
<<tria_err, fig.height=4, fig.width=4, fig.cap="Estimating the error of triangulation using standard functions in \\pnamenoindex{geosphere} assuming 95\\% of the locations fall within \\quant{} degree of the true direction of the signal. The black line contains 95\\% of the randomized locations this area is \\areaError{} hectares, the black shading shows the denstiy of points.", cache=FALSE, echo=F, results='hide', message=F, warning=F>>=

samples <- data.frame(Date=c("5/1/2012", "5/1/2012", "5/1/2012", "5/1/2012", "5/1/2012", "5/2/2012", "5/2/2012", "5/2/2012", "5/2/2012", "5/2/2012"),
  	      ID=rep("Bat_10", 10),
		      Freq=rep(149.4550, 10),
		      Time=c("21:18:00", "21:48:00", "22:18:00", "22:48:00", "23:18:00", "21:18:00", "21:48:00", "22:18:00", "22:48:00", "23:18:00"),
		      Y1=c(47.69126, 47.69126, 47.68626, 47.69113, 47.69584, 47.68626, 47.69109, 47.68626, 47.68626, 47.69109),
		      X1=c(9.06707, 9.06707, 9.10049, 9.06702, 9.12333, 9.10049, 9.06701, 9.10049, 9.10049, 9.06701),
		      B1=c(62, 80, 16, 70, 193, 330, 66, 290, 34, 68),
		      Y2=c(47.70344, 47.68626, 47.69113, 47.70344, 47.69113, 47.70322, 47.70322, 47.69109, 47.70322, 47.68626),
		      X2=c(9.09704, 9.10049, 9.06702, 9.09704, 9.06702, 9.09713, 9.09713, 9.06701, 9.09713, 9.10049),
		      B2=c(210, 334, 80, 118, 80, 252, 205, 78, 148, 54))

library("geosphere")
samples
gcIntersectBearing(samples[, c("X1", "Y1")], samples[,"B1"], samples[, c("X2", "Y2")], samples[,"B2"])

suppressMessages(library('circular'))
set.seed(213432)
loc<-2
n<-5000000
k<-504.63
B1<-as.numeric((circular(samples[loc,'B1'], units='degrees', type='direction')+rvonmises(n, circular(0,units='degrees',type='angle'),k ))%%360)
B2<-as.numeric((circular(samples[loc,'B2'], units='degrees', type='direction')+rvonmises(n, circular(0,units='degrees',type='angle'),k ))%%360)
quant<-quantile(abs(c(B1-samples[loc,'B1'], B2-samples[loc,'B2'])),.95)
suppressMessages(library('move'))
suppressMessages(library('rgeos'))
pos <- gcIntersectBearing(samples[loc, c("X1", "Y1")], samples[loc,"B1"], 
			  samples[loc, c("X2", "Y2")], samples[loc,"B2"])[,1:2]
rPos<-data.frame(gcIntersectBearing(samples[loc, c("X1", "Y1")], B1, samples[loc, c("X2", "Y2")], B2)[,1:2])
r<-SpatialPoints(rPos)
rRas<-data.frame(rasterToPoints(ras<-rasterize(r, raster(extent(r), ncol=75, nrow=75), fun='count')))
ras[is.na(ras)]<-0
ras<-new('.UD', ras/cellStats(ras, 'sum'))
con<-raster2contour(ras,level=.95)
areaError<-gArea(spTransform(a<-SpatialPolygons(list(Polygons(lapply(coordinates(con)[[1]], Polygon),'a')),proj4string=CRS('+proj=longlat')), CRS('+proj=aeqd +lon_0=9.08 +lat_0=49.70')))/100^2

suppressMessages(library('ggmap'))
trackPoints<-rbind(samples[loc,c('X1','Y1','B1')], unlist(samples[loc,c('X2','Y2','B2')]))
pos<-rbind(pos, unlist(samples[loc,c('X1','Y1')]))
pos<-rbind(pos, unlist(samples[loc,c('X2','Y2')]))
m<-get_map(bbox(.021+(s<-extent(SpatialPoints(rbind(pos, rPos))))))
s<-s+.0015
trackPointsRange<-cbind(rbind(trackPoints,trackPoints) ,rbind( destPoint(trackPoints[,c('X1','Y1')], trackPoints$B1+quant, c(500,500)),
			destPoint(trackPoints[,c('X1','Y1')], trackPoints$B1-quant, c(500,500))
			))
trackPoints<-cbind(trackPoints,destPoint(trackPoints[,c('X1','Y1')], trackPoints$B1, c(500,500)))
ggmap(m)+xlim(xmin(s), xmax(s))+ylim(ymin(s), ymax(s))+
geom_tile(data=rRas, aes(x=x,y=y,alpha=layer)) +
geom_segment(data=trackPointsRange, aes(x=X1, y=Y1, xend=lon, yend=lat), col='blue')+
geom_point(data=trackPoints, aes(x=X1, y=Y1), col='red', size=3)+
geom_segment(data=trackPoints, aes(x=X1, y=Y1, xend=lon, yend=lat), col='red')+
scale_alpha_continuous(range=(0:1))+
theme_minimal()+xlab('Longitude')+ylab('Latitude')+
geom_polygon(data=con, aes(x=long, y=lat, group=group), fill=NA, colour='black')+theme(legend.position='none')
@

\end{frame}

\begin{frame}{Data structures: Lagragian}
Ironically, most methods of analysis did/do not explicitely take into account location error. New methods take error into account (we'll deal with that later). 
Due to the ubiquity of movement data collected as a sequence of locations in time, most analytical and even data bases concentrate on Lagragian type of data.
One important aspect preceding all analyses is data standardisation and data stratification.
For this course, we will concentrate on movebank.org. There are other data bases, of course.

Movebank presentation.

\end{frame}

\begin{frame}{Data sets}
We will be working, depending on the context and suitability, with a few different sample data sets.
\begin{itemize}
\item{Bat radio tracking data}
\item{African buffalo GPS data}
\item{"Leo" the vulture}
\item{"Leroy" and "Ricky" two fishers from Albany}
\end{itemize}
These data sets can be all found on movebank, or as data associated with the R library \texttt{move}.
\end{frame}


\end{document}

 